# Generated by Django 6.1 on 2026-08-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la finca', max_length=200)),
                ('nit', models.CharField(blank=True, help_text='NIT / RUT de la empresa', max_length=50, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud (ej: 4.7110)', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud (ej: -74.0721)', max_digits=10, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, help_text='Área total en hectáreas', max_digits=10, null=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('zona_horaria', models.CharField(default='America/Bogota', help_text='Zona horaria de la finca', max_length=50)),
                ('moneda', models.CharField(default='COP', help_text='Moneda local (COP, USD, EUR)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Activo: la finca está operativa')),
                ('descripcion', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fincas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['nombre'],
            },
        ),
    ]
