# Generated by Django 6.1 on 2026-08-08 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finca',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='finca',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='finca',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AlterField(
            model_name='finca',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='finca',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='finca',
            name='zona_horaria',
            field=models.CharField(default='America/Bogota', max_length=50),
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('potrero', 'Potrero'), ('corral', 'Corral'), ('encierro', 'Encierro'), ('embarcadero', 'Embarcadero'), ('otro', 'Otro')], default='potrero', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_animales', models.IntegerField(blank=True, null=True)),
                ('carga_actual', models.IntegerField(default=0)),
                ('tipo_pasto', models.CharField(blank=True, max_length=100)),
                ('calidad_pasto', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('descanso', 'En descanso'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('dias_descanso', models.IntegerField(default=0)),
                ('fecha_ultimo_pastoreo', models.DateField(blank=True, null=True)),
                ('poligono_wkt', models.TextField(blank=True, help_text='Formato: POLYGON((lon1 lat1, lon2 lat2, ...))')),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potreros', to='core.finca')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('finca', 'codigo')},
            },
        ),
    ]
