# Generated by Django 6.1 on 2026-08-09 01:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finca_options_alter_finca_area_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='potrero',
            name='poligono_wkt',
        ),
        migrations.AddField(
            model_name='finca',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='potrero',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='potrero',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
