# Generated by Django 6.1 on 2026-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_finca_latitud_remove_finca_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potrero',
            name='area_hectareas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
