# Generated by Django 6.1 on 2026-08-10 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finca',
            options={'ordering': ['nombre'], 'verbose_name': 'Finca', 'verbose_name_plural': 'Fincas'},
        ),
        migrations.AlterModelOptions(
            name='potrero',
            options={'ordering': ['nombre'], 'verbose_name': 'Potrero', 'verbose_name_plural': 'Potreros'},
        ),
        migrations.AlterUniqueTogether(
            name='potrero',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='finca',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fincas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='potrero',
            constraint=models.UniqueConstraint(fields=('finca', 'codigo'), name='potrero_codigo_unico_por_finca'),
        ),
    ]
