# Generated by Django 6.1 on 2026-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('productividad', 'Productividad'), ('peso', 'Peso'), ('ganado', 'Ganado'), ('potreros', 'Potreros'), ('salud', 'Salud'), ('economia', 'Economía'), ('otro', 'Otro')], default='productividad', max_length=30)),
                ('unidad_resultado', models.CharField(blank=True, max_length=50)),
                ('periodicidad', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('variable', 'Variable')], default='variable', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
