# Generated by Django 6.1 on 2026-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='formula',
            field=models.TextField(blank=True, help_text='Expresión que define el cálculo de la métrica. Ejemplo: (PESO_FINAL - PESO_INICIAL) / DIAS', verbose_name='Fórmula'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='tipo_resultado',
            field=models.CharField(choices=[('numero', 'Número'), ('cantidad', 'Cantidad'), ('peso', 'Peso'), ('porcentaje', 'Porcentaje'), ('volumen', 'Volumen'), ('moneda', 'Moneda'), ('indice', 'Índice'), ('booleano', 'Verdadero / Falso')], default='numero', max_length=20, verbose_name='Tipo de resultado'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='categoria',
            field=models.CharField(choices=[('productividad', 'Productividad'), ('peso', 'Peso'), ('ganado', 'Ganado'), ('potreros', 'Potreros'), ('alimentacion', 'Alimentación'), ('reproduccion', 'Reproducción'), ('salud', 'Salud'), ('economia', 'Economía'), ('sostenibilidad', 'Sostenibilidad'), ('otro', 'Otro')], default='productividad', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='codigo',
            field=models.CharField(help_text='Identificador único utilizado por el motor de métricas. Ejemplo: GDP', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='periodicidad',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('variable', 'Variable')], default='variable', max_length=20, verbose_name='Periodicidad'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='unidad_resultado',
            field=models.CharField(blank=True, help_text='Ejemplo: kg/animal/día, litros, %, animales, COP.', max_length=50, verbose_name='Unidad del resultado'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
    ]
