# Generated by Django 6.1 on 2026-08-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_metrica_formula_metrica_tipo_resultado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Nombre utilizado dentro de la fórmula. Ejemplo: PESO_INICIAL', max_length=50, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('dato', 'Dato'), ('calculada', 'Calculada'), ('parametro', 'Parámetro')], default='dato', max_length=20, verbose_name='Tipo')),
                ('fuente', models.CharField(blank=True, help_text='Modelo o fuente de donde se obtiene el dato. Ejemplo: PesajeAnimal', max_length=100, verbose_name='Fuente')),
                ('campo', models.CharField(blank=True, help_text='Campo de la fuente utilizado. Ejemplo: peso_kg', max_length=100, verbose_name='Campo')),
                ('regla', models.CharField(choices=[('directo', 'Valor directo'), ('primero', 'Primer valor del período'), ('ultimo', 'Último valor del período'), ('promedio', 'Promedio'), ('suma', 'Suma'), ('minimo', 'Mínimo'), ('maximo', 'Máximo'), ('diferencia_fechas', 'Diferencia entre fechas')], default='directo', max_length=30, verbose_name='Regla')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='produccion.metrica', verbose_name='Métrica')),
            ],
            options={
                'verbose_name': 'Variable de Métrica',
                'verbose_name_plural': 'Variables de Métrica',
                'ordering': ['orden', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('metrica', 'codigo'), name='variable_codigo_unico_por_metrica')],
            },
        ),
    ]
