# Generated by Django 6.1 on 2026-08-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_finca_options_alter_potrero_options_and_more'),
        ('produccion', '0003_variablemetrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='finca',
            field=models.ForeignKey(blank=True, help_text='Finca propietaria de esta definición de métrica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metricas', to='core.finca', verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='codigo',
            field=models.CharField(help_text='Identificador utilizado por el motor de métricas. Ejemplo: GDP', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='metrica',
            constraint=models.UniqueConstraint(fields=('finca', 'codigo'), name='metrica_codigo_unico_por_finca'),
        ),
        migrations.AddConstraint(
            model_name='metrica',
            constraint=models.UniqueConstraint(fields=('finca', 'nombre'), name='metrica_nombre_unico_por_finca'),
        ),
    ]
