# Generated by Django 6.1 on 2026-08-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pasto',
                'verbose_name_plural': 'Tipos de Pasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='ganado.especie')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['especie', 'nombre'],
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arete', models.CharField(max_length=20, unique=True, verbose_name='Número de Arete')),
                ('nombre_propio', models.CharField(blank=True, max_length=100, verbose_name='Nombre propio')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1)),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('descartado', 'Descartado')], default='activo', max_length=20)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso actual (kg)')),
                ('preñada', models.BooleanField(default=False, verbose_name='¿Está preñada?')),
                ('fecha_ultimo_parto', models.DateField(blank=True, null=True, verbose_name='Fecha último parto')),
                ('numero_partos', models.IntegerField(default=0, verbose_name='Número de partos')),
                ('observaciones', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('potrero_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='core.potrero')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ganado.especie', verbose_name='Especie')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ganado.raza', verbose_name='Raza')),
                ('tipo_pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganado.tipopasto', verbose_name='Tipo de pasto principal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['numero_arete'],
            },
        ),
    ]
