# Generated by Django 6.1 on 2026-08-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_madre', to='ganado.animal', verbose_name='Madre (Vaca)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_padre', to='ganado.animal', verbose_name='Padre (Toro)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='porcentaje_sangre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Porcentaje de sangre / Composición genética'),
        ),
    ]
