# Generated by Django 6.1 on 2026-08-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
        ('ganado', '0002_animal_madre_animal_padre_animal_porcentaje_sangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Sigue en este potrero?')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ganado.animal')),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.potrero')),
            ],
            options={
                'verbose_name': 'Movimiento de Animal',
                'verbose_name_plural': 'Movimientos de Animales',
                'ordering': ['-fecha_entrada'],
                'unique_together': {('animal', 'fecha_entrada')},
            },
        ),
    ]
