# Generated by Django 6.1 on 2026-08-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
        ('ganado', '0003_movimientoanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='Factura / Documento')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdquisicionAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionGenetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ejemplo: 50.00', max_digits=5)),
                ('metodo', models.CharField(choices=[('pedigree', 'Pedigree'), ('registro', 'Registro oficial'), ('adn', 'ADN'), ('declaracion', 'Declaración'), ('estimacion', 'Estimación')], max_length=30)),
                ('confiabilidad', models.CharField(choices=[('confirmada', 'Confirmada'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], max_length=20)),
                ('fecha_verificacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['animal', '-porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('pedigree', 'Pedigree'), ('registro_genealogico', 'Registro genealógico'), ('adn', 'ADN / Genotipo'), ('sanitario', 'Certificado sanitario'), ('transporte', 'Documento de transporte'), ('otro', 'Otro')], max_length=40)),
                ('numero_documento', models.CharField(blank=True, max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='animales/documentos/')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('enfermedad', 'Enfermedad / Diagnóstico'), ('tratamiento', 'Tratamiento'), ('lesion', 'Lesión'), ('cirugia', 'Cirugía'), ('examen', 'Examen / Revisión'), ('consulta', 'Consulta veterinaria'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateField()),
                ('producto', models.CharField(blank=True, max_length=100, verbose_name='Producto / Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('nombre_veterinario', models.CharField(blank=True, max_length=200, verbose_name='Veterinario responsable')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento de Salud',
                'verbose_name_plural': 'Eventos de Salud',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PesajeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProcedenciaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nacimiento_granja', 'Nacimiento en la granja'), ('compra', 'Compra'), ('donacion', 'Donación'), ('traslado', 'Traslado'), ('intercambio', 'Intercambio'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('origen_nombre', models.CharField(blank=True, max_length=200, verbose_name='Origen')),
                ('origen_identificacion', models.CharField(blank=True, max_length=150, verbose_name='Identificación del origen')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movimientoanimal',
            options={'ordering': ['-fecha_entrada']},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ['especie', 'nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='movimientoanimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='fecha_ultimo_parto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='numero_partos',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='peso_actual',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='porcentaje_sangre',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='potrero_actual',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='preñada',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tipo_pasto',
        ),
        migrations.AddField(
            model_name='animal',
            name='microchip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='raza_declarada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales_declarados', to='ganado.raza', verbose_name='Raza declarada'),
        ),
        migrations.AddField(
            model_name='animal',
            name='registro_genealogico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Registro genealógico'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tatuaje',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='tipo_pasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ganado.tipopasto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='ganado.especie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('descartado', 'Descartado'), ('trasladado', 'Trasladado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendencia_materna', to='ganado.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre_propio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_arete',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de arete'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendencia_paterna', to='ganado.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='potrero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_animales', to='core.potrero'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razas', to='ganado.especie'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='raza',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='raza_unica_por_especie'),
        ),
        migrations.AddField(
            model_name='adquisicionanimal',
            name='adquisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='ganado.adquisicion'),
        ),
        migrations.AddField(
            model_name='adquisicionanimal',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adquisicion', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='composiciongenetica',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composiciones_geneticas', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='composiciongenetica',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones', to='ganado.raza'),
        ),
        migrations.AddField(
            model_name='documentoanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='eventosalud',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_salud', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='pesajeanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='procedenciaanimal',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedencia', to='ganado.animal'),
        ),
    ]
