# Generated by Django 6.1 on 2026-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0004_adquisicion_adquisicionanimal_composiciongenetica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoanimal',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
