# Generated by Django 6.1 on 2026-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
        ('ganado', '0005_alter_movimientoanimal_fecha_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composiciongenetica',
            options={'ordering': ['animal', '-porcentaje'], 'verbose_name': 'Composición genética', 'verbose_name_plural': 'Composiciones genéticas'},
        ),
        migrations.AlterModelOptions(
            name='movimientoanimal',
            options={'ordering': ['-fecha_entrada'], 'verbose_name': 'Movimiento de Animal', 'verbose_name_plural': 'Movimientos de Animales'},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ['especie', 'nombre'], 'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
        migrations.AlterField(
            model_name='eventosalud',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='movimientoanimal',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pesajeanimal',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='pesajeanimal',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso (kg)'),
        ),
        migrations.AddIndex(
            model_name='eventosalud',
            index=models.Index(fields=['animal', '-fecha'], name='salud_animal_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pesajeanimal',
            index=models.Index(fields=['animal', '-fecha'], name='pesaje_animal_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='composiciongenetica',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='composicion_genetica_porcentaje_0_100'),
        ),
        migrations.AddConstraint(
            model_name='movimientoanimal',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('animal',), name='un_solo_movimiento_activo_por_animal'),
        ),
    ]
