# Generated by Django 6.1 on 2026-08-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_potrero_area_hectareas'),
        ('ganado', '0006_alter_composiciongenetica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisicionanimal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adquisiciones_animales', to='core.finca'),
        ),
        migrations.AddField(
            model_name='animal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='core.finca'),
        ),
        migrations.AddField(
            model_name='eventosalud',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_salud', to='core.finca'),
        ),
        migrations.AddField(
            model_name='movimientoanimal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.finca'),
        ),
        migrations.AddField(
            model_name='pesajeanimal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to='core.finca'),
        ),
        migrations.AddField(
            model_name='procedenciaanimal',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedencias_animales', to='core.finca'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_arete',
            field=models.CharField(max_length=50, verbose_name='Número de arete'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('numero_arete', 'finca'), name='arete_unico_por_finca'),
        ),
    ]
