# Generated by Django 6.1 on 2026-08-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_finca_options_alter_potrero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pasto',
                'verbose_name_plural': 'Tipos de Pasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='Factura / Documento')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquisiciones', to='core.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arete', models.CharField(max_length=50, verbose_name='Número de arete')),
                ('nombre_propio', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('microchip', models.CharField(blank=True, max_length=100)),
                ('tatuaje', models.CharField(blank=True, max_length=100)),
                ('registro_genealogico', models.CharField(blank=True, max_length=150, verbose_name='Registro genealógico')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('descartado', 'Descartado'), ('trasladado', 'Trasladado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='core.finca')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendencia_materna', to='ganado.animal')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendencia_paterna', to='ganado.animal')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='ganado.especie')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['numero_arete'],
            },
        ),
        migrations.CreateModel(
            name='AdquisicionAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('adquisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='ganado.adquisicion')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adquisicion', to='ganado.animal')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('pedigree', 'Pedigree'), ('registro_genealogico', 'Registro genealógico'), ('adn', 'ADN / Genotipo'), ('sanitario', 'Certificado sanitario'), ('transporte', 'Documento de transporte'), ('otro', 'Otro')], max_length=40)),
                ('numero_documento', models.CharField(blank=True, max_length=150)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='animales/documentos/')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ganado.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedenciaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nacimiento_granja', 'Nacimiento en la granja'), ('compra', 'Compra'), ('donacion', 'Donación'), ('traslado', 'Traslado'), ('intercambio', 'Intercambio'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('origen_nombre', models.CharField(blank=True, max_length=200, verbose_name='Origen')),
                ('origen_identificacion', models.CharField(blank=True, max_length=150, verbose_name='Identificación del origen')),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedencia', to='ganado.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razas', to='ganado.especie')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['especie', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComposicionGenetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metodo', models.CharField(choices=[('pedigree', 'Pedigree'), ('registro', 'Registro oficial'), ('adn', 'ADN'), ('declaracion', 'Declaración'), ('estimacion', 'Estimación')], max_length=30)),
                ('confiabilidad', models.CharField(choices=[('confirmada', 'Confirmada'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('desconocida', 'Desconocida')], max_length=20)),
                ('fecha_verificacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composiciones_geneticas', to='ganado.animal')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones', to='ganado.raza')),
            ],
            options={
                'verbose_name': 'Composición genética',
                'verbose_name_plural': 'Composiciones genéticas',
                'ordering': ['animal', '-porcentaje'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='raza_declarada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales_declarados', to='ganado.raza', verbose_name='Raza declarada'),
        ),
        migrations.CreateModel(
            name='MovimientoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ganado.animal')),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_animales', to='core.potrero')),
                ('tipo_pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ganado.tipopasto')),
            ],
            options={
                'verbose_name': 'Movimiento de Animal',
                'verbose_name_plural': 'Movimientos de Animales',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='EventoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('enfermedad', 'Enfermedad / Diagnóstico'), ('tratamiento', 'Tratamiento'), ('lesion', 'Lesión'), ('cirugia', 'Cirugía'), ('examen', 'Examen / Revisión'), ('consulta', 'Consulta veterinaria'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('producto', models.CharField(blank=True, max_length=100, verbose_name='Producto / Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('nombre_veterinario', models.CharField(blank=True, max_length=200, verbose_name='Veterinario responsable')),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_salud', to='ganado.animal')),
            ],
            options={
                'verbose_name': 'Evento de Salud',
                'verbose_name_plural': 'Eventos de Salud',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['animal', '-fecha'], name='salud_animal_fecha_idx')],
            },
        ),
        migrations.CreateModel(
            name='PesajeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='ganado.animal')),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['animal', '-fecha'], name='pesaje_animal_fecha_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='raza',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='raza_unica_por_especie'),
        ),
        migrations.AddConstraint(
            model_name='composiciongenetica',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='composicion_genetica_0_100'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('numero_arete', 'finca'), name='arete_unico_por_finca'),
        ),
        migrations.AddConstraint(
            model_name='movimientoanimal',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('animal',), name='un_movimiento_activo_por_animal'),
        ),
    ]
